import Head from 'next/head'
import Link from 'next/link';
import ExerciseBox from '../components/exerciseBox.js'

export default function Home() {
  return (
    <>
      <Head>
        <title>GainsKeeper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/dumbbell.svg" />
      </Head>
      <header>
        <nav>
          <p></p>
        </nav>
      </header>
      <main className="text-center">
        <Link className="w-80 h-14 my-0 mx-auto mt-10 mb-10 bg-white/80 hover:bg-white/70 focus:bg-slate-200/60 rounded-md font-bold flex items-center justify-center" href="/add-exercise">
          <p>
            + Add exercise
          </p>
        </Link>
        <ExerciseBox />
      </main>
      <footer>
      </footer>
    </>
  )
}